#S3
cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
    s3:
      bucket: 
    region:
      static:
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
